source 'https://rubygems.org'

gem 'omniauth-github'
gem 'pg'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-flash'

group :test, :development do
  gem 'capybara'
  gem 'dotenv'
  gem 'pry'
  gem 'rspec'
  gem 'factory_girl'
  gem 'rack_session_access'
  gem 'database_cleaner'
end
