# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 921b977e8300112bac2a21aee7d0eda2426b43cb0713c1c8f9df0225d7619c624556bc4671eaa360e2a69295eb75e2dcd0a6510f1d080078bc8ef4197f05abc7

test:
  secret_key_base: 9dc00392732274f8bdce1e302d8fe43832d51cfc4242258fc69b9806cfff7a416dd8e8aa2ad4a756f88591692f820d6d44b300f8b50e8d68fcaa719f5e3a63de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
